spring:
  application:
    name: ToDo REST API
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password: rootroot

logging:
  level:
    web: debug
    sql: debug